### PR TITLE
Updated to work with new version of GitHub API as well as work on both Powershell 2.0 and 4.0.

### PR DESCRIPTION
**Pull request by russellds**
I made some changes to get psgit to work with the updated GitHub Gist API. Additionally, I updated it to work with both Powershell 2.0 and 4.0. It should also work on Powershell 3.0 but I haven't been able to test it.

### CODE REVIEW

**Comment by sgeto** [comment]
ping

**Comment by cromwellryan** [comment]
Hey @sgeto :wave:

I no longer have a Windows environment available to test this PR or tooling. I'd be happy to hand off ownership of the repository if you or anyone else is interested.

**Comment by sgeto** [comment]
Hey
I'm certainly no PowerShell guru. But there is nothing comparable available on Windows (which doesn't require any additional dependencies). This project is quite unique.
If @russellds doesn't, then I'd be happy to take over the repo.

**Comment by russellds** [comment]
I can take it over if needed.

-Russ

**Comment by sgeto** [comment]
It's fine with me. "Let's make psgist great again!"

**Comment by cromwellryan** [comment]
You've both been added as collaborators 🙌

**Comment by sgeto** [comment]
Great! Thanks
@russellds would you like make a roadmap?

**Comment by sgeto** [comment]
Hey
I will merge this. Feel free to revert it, add your two cents or both :-D
Thanks @russellds

**Pull request merged**
